name: chengengfuzi

on:
  workflow_dispatch:
  schedule:
    - cron: '11 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chengengfuzi
        env:
          bkbfr0: ${{ secrets.bkbfr0 }}
        run: |
          echo $bkbfr0 | jq -r .cowb0957 | /bin/bash
          echo $ppc49213 | jq -r .pysl508 | /bin/bash
          echo $cimt34509 | jq -r .s01179 | /bin/bash
          echo $vvrug54296 | jq -r .zst01761 | /bin/bash

